// Mocks generated by Mockito 5.1.0 from annotations
// in quran_app/test/unit/model/api/auth_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quran_app/model/api/auth_api.dart' as _i4;
import 'package:quran_app/model/auth_model.dart' as _i2;
import 'package:quran_app/model/favorite_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthModel_0 extends _i1.Fake implements _i2.AuthModel {}

class _FakeFavoriteModel_1 extends _i1.Fake implements _i3.FavoriteModel {}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i4.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthModel> login(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [username, password]),
              returnValue: Future<_i2.AuthModel>.value(_FakeAuthModel_0()))
          as _i5.Future<_i2.AuthModel>);
  @override
  _i5.Future<_i2.AuthModel> signup(
          String? username, String? password, String? name) =>
      (super.noSuchMethod(
              Invocation.method(#signup, [username, password, name]),
              returnValue: Future<_i2.AuthModel>.value(_FakeAuthModel_0()))
          as _i5.Future<_i2.AuthModel>);
  @override
  _i5.Future<_i2.AuthModel> updateProfile(
          String? idUser, String? username, String? name, String? email) =>
      (super.noSuchMethod(
          Invocation.method(#updateProfile, [idUser, username, name, email]),
          returnValue:
              Future<_i2.AuthModel>.value(_FakeAuthModel_0())) as _i5
          .Future<_i2.AuthModel>);
  @override
  _i5.Future<_i3.FavoriteModel> getAllFavorites(String? idUser) =>
      (super.noSuchMethod(Invocation.method(#getAllFavorites, [idUser]),
              returnValue:
                  Future<_i3.FavoriteModel>.value(_FakeFavoriteModel_1()))
          as _i5.Future<_i3.FavoriteModel>);
  @override
  _i5.Future<_i3.FavoriteModel> getFavorite(String? idUser, int? numberSurah) =>
      (super.noSuchMethod(
              Invocation.method(#getFavorite, [idUser, numberSurah]),
              returnValue:
                  Future<_i3.FavoriteModel>.value(_FakeFavoriteModel_1()))
          as _i5.Future<_i3.FavoriteModel>);
  @override
  _i5.Future<_i3.FavoriteModel> addFavorite(String? idUser, int? numberSurah) =>
      (super.noSuchMethod(
              Invocation.method(#addFavorite, [idUser, numberSurah]),
              returnValue:
                  Future<_i3.FavoriteModel>.value(_FakeFavoriteModel_1()))
          as _i5.Future<_i3.FavoriteModel>);
  @override
  _i5.Future<_i3.FavoriteModel> removeFavorite(
          String? idUser, int? numberSurah) =>
      (super.noSuchMethod(
              Invocation.method(#removeFavorite, [idUser, numberSurah]),
              returnValue:
                  Future<_i3.FavoriteModel>.value(_FakeFavoriteModel_1()))
          as _i5.Future<_i3.FavoriteModel>);
}
