// Mocks generated by Mockito 5.1.0 from annotations
// in quran_app/test/unit/model/api/quran_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quran_app/model/api/quran_api.dart' as _i4;
import 'package:quran_app/model/detail_surah_model.dart' as _i3;
import 'package:quran_app/model/surah_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSurahModel_0 extends _i1.Fake implements _i2.SurahModel {}

class _FakeDetailSurahModel_1 extends _i1.Fake implements _i3.DetailSurahModel {
}

/// A class which mocks [QuranApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranApi extends _i1.Mock implements _i4.QuranApi {
  MockQuranApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SurahModel> getAllSurah() =>
      (super.noSuchMethod(Invocation.method(#getAllSurah, []),
              returnValue: Future<_i2.SurahModel>.value(_FakeSurahModel_0()))
          as _i5.Future<_i2.SurahModel>);
  _i5.Future<_i3.DetailSurahModel> getSurah(int? number) =>
      (super.noSuchMethod(Invocation.method(#getSurah, [number]),
              returnValue:
                  Future<_i3.DetailSurahModel>.value(_FakeDetailSurahModel_1()))
          as _i5.Future<_i3.DetailSurahModel>);
}
